version: 0.0

os: linux

files:
  - source: /helloworld-1.1.jar
    destination: /tmp

hooks:
  ApplicationStop:
    - location: stop-process.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: start-process.sh
      timeout: 180
      runas: root
