version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:463146931926::task-definition/java-demo-ec2:5"
        LoadBalancerInfo:
          ContainerName: "javaContainer"
          ContainerPort: 8080
