version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - export CODEARTIFACT_AUTH_TOKEN=eyJ2ZXIiOjEsImlzdSI6MTY0OTE1NzI3NywiZW5jIjoiQTEyOEdDTSIsInRhZyI6IndmTVhCVHF5TUg4OC1kS0diMDVFNUEiLCJleHAiOjE2NDkyMDA0NzcsImFsZyI6IkExMjhHQ01LVyIsIml2IjoiVVdrSVNBdUhoSXFtTTBxUiJ9.a5pHc-fcp3wXtz-cop6L-g.gJz689LKPWWMoCfk.EGyfVSINm3Eewue3pl0lIIEDJXRb4ckaWDcCbQIEA9Cm--zsXMAKC_n0wFhRGT-F479uzIJ41sSTnSmQVrHrnmWD5wxMR-JDsaAIpkr7Tp5s1_35qkwTNbMZDyc4HbKtDmK-ZAXRgAscZUEx_6Pd7XVjFP0GSIS8MdlX4OOWe8zM7AEOwnGM6xgyIqG8fCaa4bY6Q_tT-ihns6ycIWB2jXVr7mhctdZojyZSAgWHeChT94WJtt7nDB3zLWXb8LLkJnBwQ2HC_4tY8tLX4H09PtErm8xziqlV6qkq5Gt6m_6LID6xN6zAmPBmM7aatG9TTmgviPl4fLrRUYLLFewOuXO7-FKfJbS7RcaoWntfjlqhMImC4ERUmOsRpDphCsfq6r00ZbDUfjXIFVkzwytrkEgNIb0_BxYMlmB_UrReclGyknItzDafk5si_ZIeZGsArYKsnocB77tUUCjWd-V-Zi-ClXreIjQq2lLNuWkUDxfYkER0fvVdXYpM4JAaav6m6hTa-7WzT6L9d3RAQZNsg9jEtszu_tkjU456YJD-DpQEJNY6BW30objxKDGlTWCdmAK7Vfe9g1eTLtWbSa0dVrrfJnUz230grMnzEdfn_JWzxAyiUrABofRlFFiC2jsDarTkwg1uXs78mXmnfWkOacNg8_N8k4gNamaHGOwUPeb58M4EM5-OIGWxxc0Xwl62ZW93_J1bDmXlSgjcALzWaFeqp3mZVS1O3vZdbhdMMX85EKkVRr6yxpMHlPPNao9Rhun2K_s1rGWAHzQgq3Be3G6pS3ddeQ10GwLtNstDSw5BiOYecVZhM4mpdEqBi9TOky09GKg0iVmHueGzMa0jREAdsot5lxqoDMhEY5X-du2nL9zSjMRY6J1ijRnsDMvd3jcnVReqjVHCe0yNwQ.Do41j0M3KQjwPeuH-tWpvw
      
  build:
    commands:
      - echo Build started on `date`
      - mvn deploy
  post_build:
    commands:
      - echo Build completed on `date`
      
artifacts:
  files:
    - target/helloworld-1.0.jar
