version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain java-hello --domain-owner 463146931926 --query authorizationToken --output text`
      - cat /root/.m2/settings.xml

  build:
    commands:
      - echo Build started on `date`
      - mvn deploy
  post_build:
    commands:
      - echo Build completed on `date`
      - cat /root/.m2/settings.xml
artifacts:
  files:
    - target/helloworld-1.0.jar
